# Generated by scripts/gen-formula.sh — do not edit by hand.
class Whisperdrop < Formula
  desc "Send and receive files over LAN or an encrypted tunnel, from the screen edge or the CLI"
  homepage "https://github.com/kridsadar357/whisperdrop"
  version "0.4.3"

  on_macos do
    on_arm do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.3/whisperdrop-0.4.3-aarch64-apple-darwin.tar.gz"
      sha256 "b6a4983133914f1283c784c570d8484f6dbfbe20efd195cd23e0cd6a8c1baeb6"
    end
    on_intel do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.3/whisperdrop-0.4.3-x86_64-apple-darwin.tar.gz"
      sha256 "f73c5ba5a6158195aae4d339ad5abe2878088dd259f08bdde69f5490bc327454"
    end
  end

  on_linux do
    url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.3/whisperdrop-0.4.3-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "76a77bd38aa7032871a0b4d3229291b6b0e64afdb489a2691be8a825432dcb31"
  end

  def install
    bin.install "whisperdrop"
  end

  def caveats
    <<~EOS
      Run `whisperdrop` to start the app (receiver + edge drop zone + tunnel),
      or use it from any shell:  whisperdrop send <file> --to <device|ip|group>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whisperdrop --version")
  end
end
