# Generated by scripts/gen-formula.sh — do not edit by hand.
class Whisperdrop < Formula
  desc "Send and receive files over LAN or an encrypted tunnel, from the screen edge or the CLI"
  homepage "https://github.com/kridsadar357/whisperdrop"
  version "0.4.2"

  on_macos do
    on_arm do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.2/whisperdrop-0.4.2-aarch64-apple-darwin.tar.gz"
      sha256 "2cbf62d56101628acb8657fac56abd11ebdf2038e7716a7005514631ed5c8829"
    end
    on_intel do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.2/whisperdrop-0.4.2-x86_64-apple-darwin.tar.gz"
      sha256 "64f4669b49cdc3c885b35def0bd45ba3dcc534433ca9dcfc471eeb5600de250d"
    end
  end

  on_linux do
    url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.2/whisperdrop-0.4.2-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "159fe4e8a1dfefe21431c93bb2403350754c7feb9621e71db47411946fe367a4"
  end

  def install
    bin.install "whisperdrop"
  end

  def caveats
    <<~EOS
      Run `whisperdrop` to start the app (receiver + edge drop zone + tunnel),
      or use it from any shell:  whisperdrop send <file> --to <device|ip|group>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whisperdrop --version")
  end
end
