# Generated by scripts/gen-formula.sh — do not edit by hand.
class Whisperdrop < Formula
  desc "Send and receive files over LAN or an encrypted tunnel, from the screen edge or the CLI"
  homepage "https://github.com/kridsadar357/whisperdrop"
  version "0.4.0"

  on_macos do
    on_arm do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.0/whisperdrop-0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "4c1b4489094284ce12bc2bb6fadad7bfca7a2b967c2c5d39333bca5e8a68364d"
    end
    on_intel do
      url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.0/whisperdrop-0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "fd2fb7a026c3ef22dcbc5f408e4622d9320c623c63ff54aa60b5d1260eb3f06b"
    end
  end

  on_linux do
    url "https://github.com/kridsadar357/whisperdrop/releases/download/v0.4.0/whisperdrop-0.4.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "6dd89ad9c6f563d8f5aca5267abd1714091cf3243e95f5a80dd912f4e24b6e6d"
  end

  def install
    bin.install "whisperdrop"
  end

  def caveats
    <<~EOS
      Run `whisperdrop` to start the app (receiver + edge drop zone + tunnel),
      or use it from any shell:  whisperdrop send <file> --to <device|ip|group>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/whisperdrop --version")
  end
end
